### ISSUE TITLE
Add `pipe()` and `pump()` prelude functions

### ISSUE THREAD

**Issue by raystubbs** [ten-lang/libten#11]
Two additional functions that might be good candidates for the prelude are `pipe()` and `pump()`; the first of which takes a single value and passes it through a pipeline of functions to produce the final result:

    def result: pipe( 123, str, [ s ] show( s ) )

Similarly, the `pump()` function would take an iterator (zero arity closure), and returns another which, for each call, passes the next value of the original iterator through the pipeline.

    def iter: pump( seq( 1, 2, 3, 4 ), [ v ] v + 1, [ v ] v * 2 )
    each( iter, [ v ] show( v, N ) )

**Comment by RallyTronics** [comment]
I think this would be a nice feature, pipe in particular.

**Comment by raystubbs** [comment]
Done.
